# Generated by Django 4.2 on 2026-07-01 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('medicinas', models.ManyToManyField(blank=True, to='medicina.medicina')),
            ],
        ),
    ]
